# Generated by Django 3.2.18 on 2023-04-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cust',
            fields=[
                ('CustID', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='CustID')),
                ('Fullname', models.CharField(blank=True, max_length=150, null=True, verbose_name='Full name')),
                ('Address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('SignT', models.CharField(blank=True, max_length=50, null=True, verbose_name='SignT')),
                ('Sign1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sign1')),
                ('Sign2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sign2')),
                ('Sign3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sign3')),
                ('Notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='SignT')),
                ('LastUser', models.CharField(blank=True, max_length=50, null=True, verbose_name='LastUser')),
                ('LastimeUser', models.DateTimeField(blank=True, null=True, verbose_name='LastimeUser')),
            ],
        ),
        migrations.CreateModel(
            name='pipegrade',
            fields=[
                ('PipeGrade', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Pipe Grade')),
                ('Notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='Note')),
                ('TS', models.CharField(blank=True, max_length=30, null=True, verbose_name='TS')),
                ('YP', models.CharField(blank=True, max_length=30, null=True, verbose_name='YP')),
                ('EL', models.CharField(blank=True, max_length=30, null=True, verbose_name='EL')),
                ('Hardness', models.CharField(blank=True, max_length=30, null=True, verbose_name='Hardness')),
                ('Other', models.CharField(blank=True, max_length=30, null=True, verbose_name='Other')),
                ('ChC', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChC')),
                ('ChSi', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChSi')),
                ('ChMn', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChMn')),
                ('ChP', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChP')),
                ('ChS', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChS')),
                ('ChAL', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChAL')),
                ('ChNi', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChNi')),
                ('ChCr', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChCr')),
                ('ChMo', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChMo')),
                ('ChTi', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChTi')),
                ('ChNb', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChNb')),
                ('ChZr', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChZr')),
                ('ChN', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChN')),
                ('LastUser', models.CharField(blank=True, max_length=50, null=True, verbose_name='LastUser')),
                ('LastimeUser', models.DateTimeField(blank=True, null=True, verbose_name='LastimeUser')),
            ],
        ),
    ]
