# Generated by Django 3.2.18 on 2023-04-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoilGrade',
            fields=[
                ('CoilGrade', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Pipe Grade')),
                ('Notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='Note')),
                ('LastUser', models.CharField(blank=True, max_length=50, null=True, verbose_name='LastUser')),
                ('LastimeUser', models.DateTimeField(blank=True, null=True, verbose_name='LastimeUser')),
            ],
        ),
    ]
