# Generated by Django 3.2.18 on 2023-04-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0002_coilgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coilgrade',
            name='CoilGrade',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Coil Grade'),
        ),
    ]
