# Generated by Django 3.2.18 on 2023-04-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0003_alter_coilgrade_coilgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(blank=True, max_length=500, null=True, verbose_name='Test Name')),
            ],
        ),
    ]
