# Generated by Django 3.2.18 on 2023-04-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0038_remove_cs_testname'),
        ('set', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
