# Generated by Django 3.2.18 on 2023-05-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0005_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipegrade',
            name='Flaring',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Flaring'),
        ),
        migrations.AddField(
            model_name='pipegrade',
            name='Flattening',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Flattening 0'),
        ),
        migrations.AddField(
            model_name='pipegrade',
            name='Flattening90',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Flattening 90'),
        ),
    ]
