# Generated by Django 3.2.18 on 2023-05-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0006_auto_20230506_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipegrade',
            name='Straightness',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Straightness'),
        ),
    ]
