# Generated by Django 3.2.18 on 2023-05-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0008_pipegrade_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='tmp',
            fields=[
                ('PipeGrade', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Pipe Grade')),
                ('Index', models.FloatField(blank=True, max_length=20, null=True, verbose_name='Index')),
            ],
        ),
    ]
