# Generated by Django 3.2.18 on 2023-05-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0009_tmp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tmp',
        ),
    ]
