# Generated by Django 3.2.18 on 2023-05-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0010_delete_tmp'),
    ]

    operations = [
        migrations.CreateModel(
            name='tmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PipeGrade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pipe Grade')),
                ('Index', models.FloatField(blank=True, max_length=20, null=True, verbose_name='Index')),
            ],
        ),
    ]
