# Generated by Django 3.2.18 on 2023-05-09 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0013_alter_pipegrade_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipegrade',
            name='T',
        ),
    ]
