# Generated by Django 3.2.18 on 2023-05-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0017_emailreport_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailreport',
            name='ActionName',
            field=models.CharField(blank=True, choices=[('SAAppNote', 'Receive SA approved notice'), ('CSDeadline', 'The deadline for the CS is approaching'), ('Other', 'Other notice')], max_length=10, null=True, verbose_name='Action'),
        ),
    ]
