# Generated by Django 3.2.18 on 2023-03-24 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0002_auto_20230323_0951'),
        ('cs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='SANo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sa.sa', verbose_name='SA Number'),
        ),
    ]
