# Generated by Django 3.2.18 on 2023-04-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0006_auto_20230401_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='PCManJudgment',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='PC Judgm'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='PRManJudgment',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='PR Judgm'),
        ),
    ]
