# Generated by Django 3.2.18 on 2023-04-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0008_auto_20230401_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='DLine',
            field=models.DateTimeField(verbose_name='Dead line'),
        ),
    ]
