# Generated by Django 3.2.18 on 2023-04-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0009_alter_cs_dline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='AdjID',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Adj ID'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='AdjL',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Adj L'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='AdjOD',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Adj OD'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='AdjWT',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Adj WT'),
        ),
    ]
