# Generated by Django 3.2.18 on 2023-04-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0011_auto_20230401_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='ASManDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
