# Generated by Django 3.2.18 on 2023-04-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0013_auto_20230401_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='DGDJudgment',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG'), ('Remark', 'Remark')], max_length=15, null=True, verbose_name='DGD'),
        ),
    ]
