# Generated by Django 3.2.18 on 2023-04-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0014_alter_cs_dgdjudgment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='CustID',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Cust. ID'),
        ),
    ]
