# Generated by Django 3.2.18 on 2023-04-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0015_alter_cs_custid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='CVerNote',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ver note'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='EstFDeli',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Est. Deli.'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='EstFQty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Est. F.Qty'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='EstQty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Est. Qty'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='EstTime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Est. Time'),
        ),
    ]
