# Generated by Django 3.2.18 on 2023-04-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0016_auto_20230402_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='EstFQty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Est.F.Qty'),
        ),
    ]
