# Generated by Django 3.2.18 on 2023-04-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0017_alter_cs_estfqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='EstFQty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='E.F.Qty'),
        ),
    ]
