# Generated by Django 3.2.18 on 2023-04-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0018_alter_cs_estfqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='EstFDeli',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='E. Deli.'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='EstTime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='E. Time'),
        ),
    ]
