# Generated by Django 3.2.18 on 2023-04-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0021_alter_cs_pipegrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='cust',
            fields=[
                ('CustID', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='CustID')),
                ('Fullname', models.CharField(blank=True, max_length=150, null=True, verbose_name='Full name')),
                ('Address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('SignT', models.CharField(blank=True, max_length=50, null=True, verbose_name='SignT')),
                ('Sign1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sign1')),
                ('Sign2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sign2')),
                ('Sign3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sign3')),
                ('Notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='SignT')),
                ('LastUser', models.CharField(blank=True, max_length=50, null=True, verbose_name='LastUser')),
                ('LastimeUser', models.DateTimeField(blank=True, null=True, verbose_name='LastimeUser')),
            ],
        ),
    ]
