# Generated by Django 3.2.18 on 2023-04-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0024_alter_cs_custid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='NewInq',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Modi1', 'Modify Case 1'), ('Modi2', 'Modify Case 2')], max_length=15, null=True, verbose_name='New Inquiry'),
        ),
    ]
