# Generated by Django 3.2.18 on 2023-04-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0026_alter_cs_preby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='NewInq',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Modi1', 'Modify Case 1'), ('Modi2', 'Modify Case 2')], max_length=15, null=True, verbose_name='Inquiry'),
        ),
    ]
