# Generated by Django 3.2.18 on 2023-04-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0027_alter_cs_newinq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='CustID',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Cust. ID'),
        ),
    ]
