# Generated by Django 3.2.18 on 2023-04-07 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0001_initial'),
        ('cs', '0028_alter_cs_custid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cust',
        ),
        migrations.AlterField(
            model_name='cs',
            name='CustID',
            field=models.ForeignKey(blank=True, max_length=15, null=True, on_delete=django.db.models.deletion.SET_NULL, to='set.cust', verbose_name='Customer'),
        ),
    ]
