# Generated by Django 3.2.18 on 2023-04-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0030_alter_cs_pipegrade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pipegrade',
        ),
    ]
