# Generated by Django 3.2.18 on 2023-04-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0033_alter_cs_sano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='SANo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SA Number'),
        ),
    ]
