# Generated by Django 3.2.18 on 2023-04-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0037_cs_testname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cs',
            name='testname',
        ),
    ]
