# Generated by Django 3.2.18 on 2023-04-08 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0005_delete_test'),
        ('cs', '0038_remove_cs_testname'),
    ]

    operations = [
        migrations.CreateModel(
            name='coilprocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CMaker', models.CharField(blank=True, max_length=25, null=True, verbose_name='CMaker')),
                ('CSPEC', models.CharField(blank=True, max_length=50, null=True, verbose_name='CSPEC')),
                ('CWTOrder', models.CharField(blank=True, max_length=25, null=True, verbose_name='CWTOrder')),
                ('SCoilWidth', models.CharField(blank=True, max_length=50, null=True, verbose_name='SCoilWidth')),
                ('Description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Description')),
                ('SCoilWidthPI', models.CharField(blank=True, max_length=50, null=True, verbose_name='SCoilWidthPI')),
                ('MLineQC', models.CharField(blank=True, max_length=15, null=True, verbose_name='MLineQC')),
                ('CGrade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='set.coilgrade', verbose_name='Coil Grade')),
                ('CSNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cs.cs', verbose_name='CS No')),
            ],
        ),
    ]
