# Generated by Django 3.2.18 on 2023-04-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0040_coilprocess_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='coilprocess',
            name='MLinePI',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='MLinePI'),
        ),
    ]
