# Generated by Django 3.2.18 on 2023-04-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0041_coilprocess_mlinepi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='Flattening',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Flat'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='Flattening90',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Flat 90'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='SurfLevel',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='S level'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='SurfTreat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='S Treat'),
        ),
    ]
