# Generated by Django 3.2.18 on 2023-04-10 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0043_auto_20230410_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSApproved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Note')),
                ('CSAp', models.FileField(upload_to='CSApproved/', verbose_name='Upload CS')),
                ('CSNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cs.cs', verbose_name='CS No')),
            ],
        ),
    ]
