# Generated by Django 3.2.18 on 2023-04-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0045_auto_20230410_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='EstQty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='E.Qty'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='EstTime',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='E.Tim'),
        ),
    ]
