# Generated by Django 3.2.18 on 2023-04-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0046_auto_20230410_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='csapproved',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
