# Generated by Django 3.2.18 on 2023-04-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0048_child_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csapproved',
            name='CSAp',
            field=models.FileField(blank=True, null=True, upload_to='CSApproved/', verbose_name='Upload CS'),
        ),
        migrations.AlterField(
            model_name='csapproved',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
