# Generated by Django 3.2.18 on 2023-04-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0050_alter_csapproved_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='CSAp',
            field=models.FileField(blank=True, null=True, upload_to='CSApproved/test', verbose_name='Upload CS'),
        ),
    ]
