# Generated by Django 3.2.18 on 2023-04-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0051_child_csap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csapproved',
            name='image',
        ),
    ]
