# Generated by Django 3.2.18 on 2023-04-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0052_remove_csapproved_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csapproved',
            name='Note',
        ),
        migrations.AlterField(
            model_name='csapproved',
            name='CSAp',
            field=models.FileField(null=True, upload_to='CSApproved/', verbose_name='Upload CS'),
        ),
    ]
