# Generated by Django 3.2.18 on 2023-04-16 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0053_auto_20230414_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coilprocess',
            name='CSNo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cs.cs', verbose_name='CS No'),
        ),
        migrations.AlterUniqueTogether(
            name='coilprocess',
            unique_together={('CSNo', 'No')},
        ),
    ]
