# Generated by Django 3.2.18 on 2023-04-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0054_auto_20230416_1527'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coilprocess',
            unique_together=set(),
        ),
    ]
