# Generated by Django 3.2.18 on 2023-04-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0055_alter_coilprocess_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coilprocess',
            unique_together={('CSNo', 'No')},
        ),
    ]
