# Generated by Django 3.2.18 on 2023-04-17 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0056_alter_coilprocess_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='custprocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.SmallIntegerField(default=1, verbose_name='No')),
                ('CProcess', models.CharField(blank=True, max_length=25, null=True, verbose_name='CProcess')),
                ('QCNote', models.CharField(blank=True, max_length=50, null=True, verbose_name='QCNote')),
                ('Description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Description')),
                ('CSNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cs.cs', verbose_name='CS No')),
            ],
            options={
                'unique_together': {('CSNo', 'No')},
            },
        ),
    ]
