# Generated by Django 3.2.18 on 2023-04-18 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0057_custprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RBreakdown', models.CharField(blank=True, max_length=20, null=True, verbose_name='RBreakdown')),
                ('RFinpass', models.CharField(blank=True, max_length=20, null=True, verbose_name='RFinpass')),
                ('RSGR', models.CharField(blank=True, max_length=20, null=True, verbose_name='RSGR')),
                ('RSQ', models.CharField(blank=True, max_length=20, null=True, verbose_name='RSQ')),
                ('RSizeH', models.CharField(blank=True, max_length=20, null=True, verbose_name='RSizeH')),
                ('RSizeV', models.CharField(blank=True, max_length=20, null=True, verbose_name='RSizeV')),
                ('RTH1', models.CharField(blank=True, max_length=20, null=True, verbose_name='RTH1')),
                ('TIBCHold', models.CharField(blank=True, max_length=20, null=True, verbose_name='TIBCHold')),
                ('TIBCTool', models.CharField(blank=True, max_length=20, null=True, verbose_name='TIBCTool')),
                ('TInpeder', models.CharField(blank=True, max_length=20, null=True, verbose_name='TInpeder')),
                ('TCutClamp', models.CharField(blank=True, max_length=20, null=True, verbose_name='TCutClamp')),
                ('TFaceClamp', models.CharField(blank=True, max_length=20, null=True, verbose_name='TFaceClamp')),
                ('TDelClamp', models.CharField(blank=True, max_length=20, null=True, verbose_name='TDelClamp')),
                ('TPlug', models.CharField(blank=True, max_length=20, null=True, verbose_name='TPlug')),
                ('TRing', models.CharField(blank=True, max_length=20, null=True, verbose_name='TRing')),
                ('Notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='Notes')),
                ('PIManjudgmen', models.CharField(blank=True, max_length=15, null=True, verbose_name='PIManjudgmen')),
                ('PIManNote', models.CharField(blank=True, max_length=50, null=True, verbose_name='PIManNote')),
                ('MLine', models.CharField(blank=True, max_length=10, null=True, verbose_name='MLine')),
                ('TtlInvest', models.CharField(blank=True, max_length=50, null=True, verbose_name='TtlInvest')),
                ('Leadtime', models.CharField(blank=True, max_length=50, null=True, verbose_name='Leadtime')),
                ('LastUser', models.CharField(blank=True, max_length=50, null=True, verbose_name='LastUser')),
                ('LastimeUser', models.DateTimeField(blank=True, null=True, verbose_name='LastimeUser')),
                ('CSNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cs.cs', verbose_name='CS No')),
            ],
        ),
    ]
