# Generated by Django 3.2.18 on 2023-04-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0058_cspi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cspi',
            name='PIManjudgmen',
        ),
        migrations.AddField(
            model_name='cspi',
            name='PIManjudgment',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='PIManjudgment'),
        ),
        migrations.AddField(
            model_name='cspi',
            name='RTH2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RTH1'),
        ),
    ]
