# Generated by Django 3.2.18 on 2023-04-18 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0060_auto_20230418_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='csqc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdjOD', models.CharField(blank=True, max_length=20, null=True, verbose_name='AdjOD')),
                ('AdjID', models.CharField(blank=True, max_length=20, null=True, verbose_name='AdjID')),
                ('AdjWT', models.CharField(blank=True, max_length=20, null=True, verbose_name='AdjWT')),
                ('AdjL', models.CharField(blank=True, max_length=20, null=True, verbose_name='AdjL')),
                ('InBead', models.CharField(blank=True, max_length=10, null=True, verbose_name='InBead')),
                ('SurfLevel', models.CharField(blank=True, max_length=10, null=True, verbose_name='SurfLevel')),
                ('SurfTreat', models.CharField(blank=True, max_length=20, null=True, verbose_name='SurfTreat')),
                ('Straight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Straight')),
                ('Flaring', models.CharField(blank=True, max_length=50, null=True, verbose_name='Flaring')),
                ('Flattening90', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('Flattening', models.CharField(blank=True, max_length=50, null=True, verbose_name='Flattening90')),
                ('SQWSPost', models.CharField(blank=True, max_length=30, null=True, verbose_name='SQWSPost')),
                ('SQConR', models.CharField(blank=True, max_length=30, null=True, verbose_name='SQConR')),
                ('PPunch', models.CharField(blank=True, max_length=30, null=True, verbose_name='PPunch')),
                ('PipeEdgeNote', models.CharField(blank=True, max_length=50, null=True, verbose_name='PipeEdgeNote')),
                ('Notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='Notes')),
                ('TS', models.CharField(blank=True, max_length=30, null=True, verbose_name='TS')),
                ('YP', models.CharField(blank=True, max_length=30, null=True, verbose_name='YP')),
                ('EL', models.CharField(blank=True, max_length=30, null=True, verbose_name='EL')),
                ('Hardness', models.CharField(blank=True, max_length=30, null=True, verbose_name='Hardness')),
                ('Other', models.CharField(blank=True, max_length=30, null=True, verbose_name='Other')),
                ('ChC', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChC')),
                ('ChSi', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChSi')),
                ('ChMn', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChMn')),
                ('ChP', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChP')),
                ('ChS', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChS')),
                ('ChAL', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChAL')),
                ('ChNi', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChNi')),
                ('ChCr', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChCr')),
                ('ChMo', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChMo')),
                ('ChTi', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChTi')),
                ('ChNb', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChNb')),
                ('ChZr', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChZr')),
                ('ChN', models.CharField(blank=True, max_length=30, null=True, verbose_name='ChN')),
                ('QAManJudgment', models.CharField(blank=True, max_length=15, null=True, verbose_name='QAManJudgment')),
                ('QAManNote', models.CharField(blank=True, max_length=50, null=True, verbose_name='QAManNote')),
                ('Description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Description')),
                ('LastUser', models.CharField(blank=True, max_length=50, null=True, verbose_name='LastUser')),
                ('CSNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cs.cs', verbose_name='CS No')),
            ],
        ),
    ]
