# Generated by Django 3.2.18 on 2023-04-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0061_csqc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csqc',
            name='Description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Des.'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='Flattening',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Flat90'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='PipeEdgeNote',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PipeENote'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='QAManJudgment',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='QA Judg'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='QAManNote',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='QA Note'),
        ),
    ]
