# Generated by Django 3.2.18 on 2023-04-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0062_auto_20230418_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csqc',
            name='Flattening90',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Flat90'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='QAManJudgment',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='QA Jud'),
        ),
    ]
