# Generated by Django 3.2.18 on 2023-04-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0067_alter_cs_dgdjudgment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csqc',
            name='PipeEdgeNote',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PENote'),
        ),
    ]
