# Generated by Django 3.2.18 on 2023-04-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0068_alter_csqc_pipeedgenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csqc',
            name='Hardness',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Hard'),
        ),
    ]
