# Generated by Django 3.2.18 on 2023-04-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0070_alter_cspi_rth2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cs',
            name='ImageSPEC',
            field=models.ImageField(blank=True, null=True, upload_to='CSImangeSPEC/', verbose_name='Image SPEC'),
        ),
    ]
