# Generated by Django 3.2.18 on 2023-05-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0071_cs_imagespec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='ImageSPEC',
            field=models.ImageField(blank=True, null=True, upload_to='CSImangeSPEC/', verbose_name='ISPEC'),
        ),
    ]
