# Generated by Django 3.2.18 on 2023-05-02 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0072_alter_cs_imagespec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='IDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Initial date'),
        ),
    ]
