# Generated by Django 3.2.18 on 2023-05-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0073_alter_cs_idate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='ImageSPEC',
            field=models.ImageField(blank=True, null=True, upload_to='CSImangeSPEC/', verbose_name='Image reference'),
        ),
    ]
