# Generated by Django 3.2.18 on 2023-05-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0075_alter_cs_cver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='ASPICNote',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='AS P.I.C.Note'),
        ),
    ]
