# Generated by Django 3.2.18 on 2023-05-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0076_alter_cs_aspicnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='PackASNote',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pack AS Note'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='PackASQty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pack AS Qty'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='PackPCNote',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pack PC Note'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='PackPCQty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pack PC Qty'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='PackUnit',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Pack Unit'),
        ),
    ]
