# Generated by Django 3.2.18 on 2023-05-03 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0077_auto_20230503_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='CVerDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Issue date'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='IDate',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Initial date'),
        ),
    ]
