# Generated by Django 3.2.18 on 2023-05-03 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0078_auto_20230503_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='IDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Initial date'),
        ),
    ]
