# Generated by Django 3.2.18 on 2023-05-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0081_auto_20230504_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='PackUnit',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Pack U.'),
        ),
    ]
