# Generated by Django 3.2.18 on 2023-05-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0084_auto_20230504_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='PipeEdgeValue',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Pipe Edge'),
        ),
    ]
