# Generated by Django 3.2.18 on 2023-05-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0085_alter_cs_pipeedgevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='InBead',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Inside Bead'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='Notes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Note/Other'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='SurfLevel',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Surface level'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='SurfTreat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Surface Treat'),
        ),
    ]
