# Generated by Django 3.2.18 on 2023-05-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0087_alter_cs_pipegrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='InBead',
            field=models.CharField(blank=True, choices=[('IBC', 'IBC'), ('NON-IBC', 'NON-IBC'), ('IB-P', 'IB-P')], max_length=10, null=True, verbose_name='Inside Bead'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='SurfLevel',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B1', 'B1'), ('B2', 'B2'), ('C', 'C')], max_length=10, null=True, verbose_name='Surface level'),
        ),
    ]
