# Generated by Django 3.2.18 on 2023-05-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0088_auto_20230505_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='cs',
            name='Density',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Kg/pcs'),
        ),
    ]
