# Generated by Django 3.2.18 on 2023-05-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0089_cs_density'),
    ]

    operations = [
        migrations.AddField(
            model_name='cs',
            name='Shape',
            field=models.CharField(blank=True, choices=[('Round', 'Round'), ('Square', 'Square'), ('Oval', 'Oval'), ('Ellipse', 'Ellipse')], max_length=10, null=True, verbose_name='Shape'),
        ),
    ]
