# Generated by Django 3.2.18 on 2023-05-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0091_auto_20230505_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='AdjID',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tolerance'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='AdjL',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tolerance'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='AdjOD',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tolerance'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='AdjWT',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tolerance'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='InBead',
            field=models.CharField(blank=True, choices=[('IBC', 'IBC'), ('NON-IBC', 'NON-IBC'), ('IB-P', 'IB-P')], max_length=10, null=True, verbose_name='IBC'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='PKind',
            field=models.CharField(blank=True, choices=[('EG', 'EG'), ('CD', 'CD'), ('EG-CD', 'EG-CD')], max_length=50, null=True, verbose_name='Process'),
        ),
    ]
