# Generated by Django 3.2.18 on 2023-05-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0098_auto_20230506_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='csqc',
            name='Straightness',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Straightness'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='Description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Description'),
        ),
    ]
