# Generated by Django 3.2.18 on 2023-05-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0100_auto_20230506_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csqc',
            name='ChAL',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='AL'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='ChC',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='C'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='ChCr',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cr'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='ChMn',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Mn'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='ChMo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Mo'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='ChN',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='N'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='ChNb',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nb'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='ChNi',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ni'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='ChP',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='P'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='ChS',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='S'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='ChSi',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Si'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='ChTi',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ti'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='ChZr',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Zr'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='Flattening',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Flattening 0'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='Flattening90',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Flattening 90'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='Hardness',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Hardness'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='PipeEdgeNote',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pipe Edge'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='QAManJudgment',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='QA Judgement'),
        ),
    ]
