# Generated by Django 3.2.18 on 2023-05-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0103_auto_20230506_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csqc',
            name='SurfLevel',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Surface Level'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='SurfTreat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Surface Treat'),
        ),
    ]
