# Generated by Django 3.2.18 on 2023-05-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0104_auto_20230507_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cspi',
            name='RBreakdown',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Breakdown'),
        ),
        migrations.AlterField(
            model_name='cspi',
            name='RFinpass',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Finpass'),
        ),
        migrations.AlterField(
            model_name='cspi',
            name='RSGR',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SGR'),
        ),
        migrations.AlterField(
            model_name='cspi',
            name='RSQ',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SQ'),
        ),
        migrations.AlterField(
            model_name='cspi',
            name='RSizeH',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Size horizonal'),
        ),
        migrations.AlterField(
            model_name='cspi',
            name='RSizeV',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Size vertical'),
        ),
        migrations.AlterField(
            model_name='cspi',
            name='RTH1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='T/H-1'),
        ),
        migrations.AlterField(
            model_name='cspi',
            name='RTH2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='T/H-2'),
        ),
        migrations.AlterField(
            model_name='cspi',
            name='TCutClamp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cut off Clamp'),
        ),
        migrations.AlterField(
            model_name='cspi',
            name='TDelClamp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Delimpler Clamp'),
        ),
        migrations.AlterField(
            model_name='cspi',
            name='TFaceClamp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Face Clamp'),
        ),
        migrations.AlterField(
            model_name='cspi',
            name='TIBCHold',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IBC Hold'),
        ),
        migrations.AlterField(
            model_name='cspi',
            name='TIBCTool',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IBC Tool'),
        ),
        migrations.AlterField(
            model_name='cspi',
            name='TInpeder',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inpeder'),
        ),
        migrations.AlterField(
            model_name='cspi',
            name='TPlug',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Plug'),
        ),
        migrations.AlterField(
            model_name='cspi',
            name='TRing',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ring'),
        ),
        migrations.AlterField(
            model_name='cspi',
            name='TtlInvest',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ttl Invest ($)'),
        ),
    ]
