# Generated by Django 3.2.18 on 2023-05-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0106_auto_20230507_1047'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coilprocess',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coilprocess',
            name='No',
        ),
    ]
