# Generated by Django 3.2.18 on 2023-05-07 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0007_pipegrade_straightness'),
        ('cs', '0107_auto_20230507_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coilprocess',
            name='CGrade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='set.coilgrade', verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='coilprocess',
            name='CMaker',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Coil Maker'),
        ),
        migrations.AlterField(
            model_name='coilprocess',
            name='CSPEC',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SPEC'),
        ),
        migrations.AlterField(
            model_name='coilprocess',
            name='CWTOrder',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='CWT Order'),
        ),
        migrations.AlterField(
            model_name='coilprocess',
            name='MLinePI',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='MLine PI'),
        ),
        migrations.AlterField(
            model_name='coilprocess',
            name='MLineQC',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='MLine QC'),
        ),
        migrations.AlterField(
            model_name='coilprocess',
            name='SCoilWidth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SCoil Width'),
        ),
    ]
