# Generated by Django 3.2.18 on 2023-05-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0108_auto_20230507_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='CVerNote',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Version note'),
        ),
    ]
