# Generated by Django 3.2.18 on 2023-05-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0110_auto_20230507_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='ASManJudgment',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG'), ('Remark', 'Remark')], max_length=15, null=True, verbose_name='AS Judg.'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='DGDJudgment',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG'), ('Remark', 'Remark')], max_length=15, null=True, verbose_name='DGD Judg.'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='PCManJudgment',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG'), ('Remark', 'Remark')], max_length=15, null=True, verbose_name='PC Judg.'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='PIManJudgment',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG'), ('Remark', 'Remark')], max_length=15, null=True, verbose_name='PI Judg.'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='PRManJudgment',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG'), ('Remark', 'Remark')], max_length=15, null=True, verbose_name='PR Judg.'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='QAManJudgment',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG'), ('Remark', 'Remark')], max_length=15, null=True, verbose_name='QA Judg.'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='QCManJudgment',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG'), ('Remark', 'Remark')], max_length=15, null=True, verbose_name='QC Judg.'),
        ),
        migrations.AlterField(
            model_name='csqc',
            name='QAManJudgment',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='QA Judg.'),
        ),
    ]
