# Generated by Django 3.2.18 on 2023-05-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0111_auto_20230508_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='cs',
            name='CSAp',
            field=models.FileField(null=True, upload_to='CSApproved/', verbose_name='Upload CS'),
        ),
    ]
