# Generated by Django 3.2.18 on 2023-05-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0112_cs_csap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='CSAp',
            field=models.FileField(null=True, upload_to='CSApproved/', verbose_name='Approved CS'),
        ),
    ]
