# Generated by Django 3.2.18 on 2023-05-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0114_alter_cs_csap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cs',
            name='Demand',
        ),
        migrations.AlterField(
            model_name='cs',
            name='EstQty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Demand'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='NewInq',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Modify', 'Modify')], max_length=15, null=True, verbose_name='Inquiry'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='PKind',
            field=models.CharField(blank=True, choices=[('EG', 'EG'), ('CD', 'CD')], max_length=50, null=True, verbose_name='Process'),
        ),
    ]
