# Generated by Django 3.2.18 on 2023-05-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0115_auto_20230509_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cs',
            name='CSAp',
        ),
    ]
