# Generated by Django 3.2.18 on 2023-05-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0117_alter_cs_density'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='PipeEdgeValue',
            field=models.CharField(blank=True, choices=[('AS', 'AS'), ('Facer', 'Facer'), ('Br', 'Br'), ('CF', 'CF')], max_length=5, null=True, verbose_name='Pipe Edge'),
        ),
    ]
