# Generated by Django 3.2.18 on 2023-05-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0118_alter_cs_pipeedgevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='PipeEdgeValue',
            field=models.CharField(blank=True, choices=[('AS', 'AS'), ('Br', 'Br'), ('CF', 'CF'), ('Facer', 'Facer')], max_length=5, null=True, verbose_name='Pipe Edge'),
        ),
    ]
