# Generated by Django 3.2.18 on 2023-05-11 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0015_surflevel'),
        ('cs', '0119_alter_cs_pipeedgevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='SurfLevel',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, to='set.surflevel', verbose_name='Surface level'),
        ),
    ]
