# Generated by Django 3.2.18 on 2023-05-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0120_alter_cs_surflevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs',
            name='DGDJudgment',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG'), ('Remark', 'Remark')], max_length=15, null=True, verbose_name='AO Judg.'),
        ),
        migrations.AlterField(
            model_name='cs',
            name='DGDNote',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='AO Note'),
        ),
    ]
