# Generated by Django 3.2.18 on 2023-05-24 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0018_alter_emailreport_actionname'),
        ('cs', '0121_auto_20230512_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coilprocess',
            name='CGrade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='set.coilgrade', verbose_name='Coil Grade'),
        ),
    ]
