# Generated by Django 3.2.18 on 2023-03-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sa',
            fields=[
                ('SANo', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='CS Number')),
                ('SAStatus', models.CharField(blank=True, max_length=50, null=True, verbose_name='SAStatus')),
                ('IDate', models.DateTimeField(verbose_name='Initial date')),
                ('SAVer', models.CharField(blank=True, max_length=2, null=True, verbose_name='SA Version')),
                ('SAVerNote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Version note')),
                ('CustID', models.CharField(blank=True, max_length=15, null=True, verbose_name='Customer ID')),
                ('PartNo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Part No')),
                ('PartName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Part Name')),
                ('PartMaker', models.CharField(blank=True, max_length=50, null=True, verbose_name='Part Maker')),
            ],
        ),
    ]
