# Generated by Django 3.2.18 on 2023-03-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sa',
            name='LastUser',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='LastUser'),
        ),
        migrations.AddField(
            model_name='sa',
            name='LastimeUser',
            field=models.DateTimeField(blank=True, null=True, verbose_name='LastimeUser'),
        ),
    ]
