# Generated by Django 3.2.18 on 2023-03-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0002_auto_20230323_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='sa',
            name='AdjID',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='AdjID'),
        ),
        migrations.AddField(
            model_name='sa',
            name='AdjL',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='AdjL'),
        ),
        migrations.AddField(
            model_name='sa',
            name='AdjOD',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='AdjOD'),
        ),
        migrations.AddField(
            model_name='sa',
            name='AdjWT',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='AdjWT'),
        ),
        migrations.AddField(
            model_name='sa',
            name='Bending',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bending'),
        ),
        migrations.AddField(
            model_name='sa',
            name='CHMo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='CHMo'),
        ),
        migrations.AddField(
            model_name='sa',
            name='ChAL',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ChAL'),
        ),
        migrations.AddField(
            model_name='sa',
            name='ChC',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ChC'),
        ),
        migrations.AddField(
            model_name='sa',
            name='ChCr',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ChCr'),
        ),
        migrations.AddField(
            model_name='sa',
            name='ChMn',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ChMn'),
        ),
        migrations.AddField(
            model_name='sa',
            name='ChN',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ChN'),
        ),
        migrations.AddField(
            model_name='sa',
            name='ChNb',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ChNb'),
        ),
        migrations.AddField(
            model_name='sa',
            name='ChNi',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ChNi'),
        ),
        migrations.AddField(
            model_name='sa',
            name='ChOthers',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ChOthers'),
        ),
        migrations.AddField(
            model_name='sa',
            name='ChP',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ChP'),
        ),
        migrations.AddField(
            model_name='sa',
            name='ChS',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ChS'),
        ),
        migrations.AddField(
            model_name='sa',
            name='ChSi',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ChSi'),
        ),
        migrations.AddField(
            model_name='sa',
            name='ChTi',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ChTi'),
        ),
        migrations.AddField(
            model_name='sa',
            name='ChZr',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ChZr'),
        ),
        migrations.AddField(
            model_name='sa',
            name='Coatching',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Coatching'),
        ),
        migrations.AddField(
            model_name='sa',
            name='DGDJudgment',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='DGDJudgment'),
        ),
        migrations.AddField(
            model_name='sa',
            name='DGDManDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='DGDManDate'),
        ),
        migrations.AddField(
            model_name='sa',
            name='EL',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='EL'),
        ),
        migrations.AddField(
            model_name='sa',
            name='Flaring',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Flaring'),
        ),
        migrations.AddField(
            model_name='sa',
            name='Flattening',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Flattening'),
        ),
        migrations.AddField(
            model_name='sa',
            name='Flattening90',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Flattening90'),
        ),
        migrations.AddField(
            model_name='sa',
            name='Hardness',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Hardness'),
        ),
        migrations.AddField(
            model_name='sa',
            name='HeatTreat',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='HeatTreat'),
        ),
        migrations.AddField(
            model_name='sa',
            name='ID',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='sa',
            name='InBead',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='InBead'),
        ),
        migrations.AddField(
            model_name='sa',
            name='InBeadH',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='InBeadH'),
        ),
        migrations.AddField(
            model_name='sa',
            name='L',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='L'),
        ),
        migrations.AddField(
            model_name='sa',
            name='Marking',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Marking'),
        ),
        migrations.AddField(
            model_name='sa',
            name='Model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='sa',
            name='NDI',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='NDI'),
        ),
        migrations.AddField(
            model_name='sa',
            name='Notes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='sa',
            name='OD',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='OD'),
        ),
        migrations.AddField(
            model_name='sa',
            name='Other',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Other'),
        ),
        migrations.AddField(
            model_name='sa',
            name='Others',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Others'),
        ),
        migrations.AddField(
            model_name='sa',
            name='PKind',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PKind'),
        ),
        migrations.AddField(
            model_name='sa',
            name='PPunch',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='PPunch'),
        ),
        migrations.AddField(
            model_name='sa',
            name='PackStd',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='PackStd'),
        ),
        migrations.AddField(
            model_name='sa',
            name='PipeEdgeNote',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PipeEdgeNote'),
        ),
        migrations.AddField(
            model_name='sa',
            name='PipeEdgeNoteT',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PipeEdgeNoteT'),
        ),
        migrations.AddField(
            model_name='sa',
            name='PipeGrade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PipeGrade'),
        ),
        migrations.AddField(
            model_name='sa',
            name='PipeStd',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PipeStd'),
        ),
        migrations.AddField(
            model_name='sa',
            name='QAManDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='QAManDate'),
        ),
        migrations.AddField(
            model_name='sa',
            name='QAManJudgment',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='QAManJudgment'),
        ),
        migrations.AddField(
            model_name='sa',
            name='QCManDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='QCManDate'),
        ),
        migrations.AddField(
            model_name='sa',
            name='QCManJudgment',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='QCManJudgment'),
        ),
        migrations.AddField(
            model_name='sa',
            name='QCRecNo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='QCRecNo'),
        ),
        migrations.AddField(
            model_name='sa',
            name='SKind',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SKind'),
        ),
        migrations.AddField(
            model_name='sa',
            name='SQConR',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='SQConR'),
        ),
        migrations.AddField(
            model_name='sa',
            name='SQWSPost',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='SQWSPost'),
        ),
        migrations.AddField(
            model_name='sa',
            name='Straight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Straight'),
        ),
        migrations.AddField(
            model_name='sa',
            name='SurfCondE',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='SurfCondE'),
        ),
        migrations.AddField(
            model_name='sa',
            name='SurfCondV',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='SurfCondV'),
        ),
        migrations.AddField(
            model_name='sa',
            name='SurfLevel',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='SurfLevel'),
        ),
        migrations.AddField(
            model_name='sa',
            name='SurfTreat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SurfTreat'),
        ),
        migrations.AddField(
            model_name='sa',
            name='TS',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='TS'),
        ),
        migrations.AddField(
            model_name='sa',
            name='Tensile',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tensile'),
        ),
        migrations.AddField(
            model_name='sa',
            name='WT',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='WT'),
        ),
        migrations.AddField(
            model_name='sa',
            name='YP',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='YP'),
        ),
    ]
