# Generated by Django 3.2.18 on 2023-04-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0003_auto_20230326_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sa',
            name='DGDJudgment',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='DGD'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='QAManJudgment',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='QA J.'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='QCManJudgment',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='QC J.'),
        ),
    ]
