# Generated by Django 3.2.18 on 2023-05-06 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0005_delete_test'),
        ('sa', '0004_auto_20230401_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sa',
            name='CustID',
            field=models.ForeignKey(blank=True, max_length=15, null=True, on_delete=django.db.models.deletion.SET_NULL, to='set.cust', verbose_name='Customer'),
        ),
    ]
