# Generated by Django 3.2.18 on 2023-05-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0006_alter_sa_pipegrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sa',
            name='DGDJudgment',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='DGD Judg.'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='QAManJudgment',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='QA Judg.'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='QCManJudgment',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='QC Judg.'),
        ),
    ]
