# Generated by Django 3.2.18 on 2023-05-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0008_auto_20230512_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sa',
            name='PipeEdgeNote',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pipe Edge'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='PipeEdgeNoteT',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pipe E Tolerance'),
        ),
    ]
