# Generated by Django 3.2.18 on 2023-05-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0012_alter_sa_pipestd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sa',
            name='HeatTreat',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Heat Treatment'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='PackStd',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Packing Std.'),
        ),
    ]
