# Generated by Django 3.2.18 on 2023-05-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0013_auto_20230512_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='sa',
            name='ImageSPEC',
            field=models.ImageField(blank=True, null=True, upload_to='SAImangeSPEC/', verbose_name='drawing reference'),
        ),
    ]
