# Generated by Django 3.2.18 on 2023-05-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0015_alter_sa_sano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sa',
            name='IDate',
            field=models.DateTimeField(verbose_name='Isue date'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='SANo',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='SA NO'),
        ),
    ]
