# Generated by Django 3.2.18 on 2023-05-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0018_alter_sa_dgdjudgment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sa',
            name='IDate',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
