# Generated by Django 3.2.18 on 2023-05-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0020_sa_saapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sa',
            name='AppDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved Date'),
        ),
    ]
