# Generated by Django 3.2.18 on 2023-05-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0022_alter_sa_pipeedgenotet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sa',
            name='AdjID',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tol. ID'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='AdjL',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tol. L'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='AdjOD',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tol. OD'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='AdjWT',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tol. WT'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='CHMo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Molybdenum'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='ChAL',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Aluminium'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='ChC',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Carbon'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='ChCr',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Chromium'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='ChMn',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Manganese'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='ChN',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nitrogen'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='ChNb',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Niobium'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='ChNi',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nickel'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='ChP',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phosphorus'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='ChS',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Sulphur'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='ChSi',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Silicon'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='ChTi',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Titanium'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='ChZr',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Zinc'),
        ),
    ]
