# Generated by Django 3.2.18 on 2023-05-17 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0023_auto_20230513_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sa',
            name='IDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
