# Generated by Django 3.2.18 on 2023-05-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0024_alter_sa_idate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sa',
            name='InBeadH',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='IB Height'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='QCRecNo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Record No'),
        ),
    ]
