# Generated by Django 3.2.18 on 2023-05-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sa', '0025_auto_20230517_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sa',
            name='SurfCondE',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Surface Condition English'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='SurfCondV',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Surface Condition Vietnamese'),
        ),
        migrations.AlterField(
            model_name='sa',
            name='SurfTreat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Surface Treat'),
        ),
    ]
